version: '3.1'
services:
  mysql_dev:
    container_name: 'mysql-dev-responde'
    image: 'mysql:latest'
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/data/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
  mailcatcher:
    container_name: mailcatcher-responde
    image: sj26/mailcatcher
    expose:
      - 1025
      - 1080
    ports:
      - 1025:1025
      - 1080:1080
volumes:
  mysql_data:
