version: '2.4'
services:
  postgres_dev:
    container_name: 'dev-responde'
    image: 'mysql:latest'
    env_file:
      - ../.env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/data/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  mysql_data:
